//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hours.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int runs {
            get {
                return ((int)(this["runs"]));
            }
            set {
                this["runs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int mode {
            get {
                return ((int)(this["mode"]));
            }
            set {
                this["mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.2")]
        public double all_opacity {
            get {
                return ((double)(this["all_opacity"]));
            }
            set {
                this["all_opacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public double all_size {
            get {
                return ((double)(this["all_size"]));
            }
            set {
                this["all_size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool all_top {
            get {
                return ((bool)(this["all_top"]));
            }
            set {
                this["all_top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double all_wleft {
            get {
                return ((double)(this["all_wleft"]));
            }
            set {
                this["all_wleft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double all_wtop {
            get {
                return ((double)(this["all_wtop"]));
            }
            set {
                this["all_wtop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool zobraz_pocasi {
            get {
                return ((bool)(this["zobraz_pocasi"]));
            }
            set {
                this["zobraz_pocasi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool tikani {
            get {
                return ((bool)(this["tikani"]));
            }
            set {
                this["tikani"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alarm {
            get {
                return ((bool)(this["alarm"]));
            }
            set {
                this["alarm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public string alarmHodiny {
            get {
                return ((string)(this["alarmHodiny"]));
            }
            set {
                this["alarmHodiny"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string alarmMinuty {
            get {
                return ((string)(this["alarmMinuty"]));
            }
            set {
                this["alarmMinuty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool auto {
            get {
                return ((bool)(this["auto"]));
            }
            set {
                this["auto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string autoHodiny {
            get {
                return ((string)(this["autoHodiny"]));
            }
            set {
                this["autoHodiny"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string autoMinuty {
            get {
                return ((string)(this["autoMinuty"]));
            }
            set {
                this["autoMinuty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string barvaHodin {
            get {
                return ((string)(this["barvaHodin"]));
            }
            set {
                this["barvaHodin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string barvaH {
            get {
                return ((string)(this["barvaH"]));
            }
            set {
                this["barvaH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string barvaM {
            get {
                return ((string)(this["barvaM"]));
            }
            set {
                this["barvaM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string barvaS {
            get {
                return ((string)(this["barvaS"]));
            }
            set {
                this["barvaS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string barvaStred {
            get {
                return ((string)(this["barvaStred"]));
            }
            set {
                this["barvaStred"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string barvaC {
            get {
                return ((string)(this["barvaC"]));
            }
            set {
                this["barvaC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string alarmMusic {
            get {
                return ((string)(this["alarmMusic"]));
            }
            set {
                this["alarmMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool w_city {
            get {
                return ((bool)(this["w_city"]));
            }
            set {
                this["w_city"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool w_temp {
            get {
                return ((bool)(this["w_temp"]));
            }
            set {
                this["w_temp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool w_info {
            get {
                return ((bool)(this["w_info"]));
            }
            set {
                this["w_info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool w_obr {
            get {
                return ((bool)(this["w_obr"]));
            }
            set {
                this["w_obr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool w_datum {
            get {
                return ((bool)(this["w_datum"]));
            }
            set {
                this["w_datum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string c_podkladA {
            get {
                return ((string)(this["c_podkladA"]));
            }
            set {
                this["c_podkladA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string c_stredA {
            get {
                return ((string)(this["c_stredA"]));
            }
            set {
                this["c_stredA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string c_hodinaA {
            get {
                return ((string)(this["c_hodinaA"]));
            }
            set {
                this["c_hodinaA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string c_minutaA {
            get {
                return ((string)(this["c_minutaA"]));
            }
            set {
                this["c_minutaA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string c_sekundaA {
            get {
                return ((string)(this["c_sekundaA"]));
            }
            set {
                this["c_sekundaA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string c_cifernikA {
            get {
                return ((string)(this["c_cifernikA"]));
            }
            set {
                this["c_cifernikA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool c0_msec {
            get {
                return ((bool)(this["c0_msec"]));
            }
            set {
                this["c0_msec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool c0_sec {
            get {
                return ((bool)(this["c0_sec"]));
            }
            set {
                this["c0_sec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool c0_min {
            get {
                return ((bool)(this["c0_min"]));
            }
            set {
                this["c0_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool c0_hour {
            get {
                return ((bool)(this["c0_hour"]));
            }
            set {
                this["c0_hour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool c1_msec {
            get {
                return ((bool)(this["c1_msec"]));
            }
            set {
                this["c1_msec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool c1_sec {
            get {
                return ((bool)(this["c1_sec"]));
            }
            set {
                this["c1_sec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool c1_min {
            get {
                return ((bool)(this["c1_min"]));
            }
            set {
                this["c1_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool c1_hour {
            get {
                return ((bool)(this["c1_hour"]));
            }
            set {
                this["c1_hour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool c0_mid {
            get {
                return ((bool)(this["c0_mid"]));
            }
            set {
                this["c0_mid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool c0_cif {
            get {
                return ((bool)(this["c0_cif"]));
            }
            set {
                this["c0_cif"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool c0_pod {
            get {
                return ((bool)(this["c0_pod"]));
            }
            set {
                this["c0_pod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_msecx_R {
            get {
                return ((string)(this["c0_msecx_R"]));
            }
            set {
                this["c0_msecx_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_msecx_G {
            get {
                return ((string)(this["c0_msecx_G"]));
            }
            set {
                this["c0_msecx_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_msecx_B {
            get {
                return ((string)(this["c0_msecx_B"]));
            }
            set {
                this["c0_msecx_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_msecx_O {
            get {
                return ((string)(this["c0_msecx_O"]));
            }
            set {
                this["c0_msecx_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_msecx_S {
            get {
                return ((string)(this["c0_msecx_S"]));
            }
            set {
                this["c0_msecx_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_msecx_F {
            get {
                return ((string)(this["c0_msecx_F"]));
            }
            set {
                this["c0_msecx_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_secx_R {
            get {
                return ((string)(this["c0_secx_R"]));
            }
            set {
                this["c0_secx_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_secx_G {
            get {
                return ((string)(this["c0_secx_G"]));
            }
            set {
                this["c0_secx_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_secx_B {
            get {
                return ((string)(this["c0_secx_B"]));
            }
            set {
                this["c0_secx_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_secx_O {
            get {
                return ((string)(this["c0_secx_O"]));
            }
            set {
                this["c0_secx_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_secx_S {
            get {
                return ((string)(this["c0_secx_S"]));
            }
            set {
                this["c0_secx_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_secx_F {
            get {
                return ((string)(this["c0_secx_F"]));
            }
            set {
                this["c0_secx_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_minx_R {
            get {
                return ((string)(this["c0_minx_R"]));
            }
            set {
                this["c0_minx_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_minx_G {
            get {
                return ((string)(this["c0_minx_G"]));
            }
            set {
                this["c0_minx_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_minx_B {
            get {
                return ((string)(this["c0_minx_B"]));
            }
            set {
                this["c0_minx_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_minx_O {
            get {
                return ((string)(this["c0_minx_O"]));
            }
            set {
                this["c0_minx_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_minx_S {
            get {
                return ((string)(this["c0_minx_S"]));
            }
            set {
                this["c0_minx_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_minx_F {
            get {
                return ((string)(this["c0_minx_F"]));
            }
            set {
                this["c0_minx_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_hourx_R {
            get {
                return ((string)(this["c0_hourx_R"]));
            }
            set {
                this["c0_hourx_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_hourx_G {
            get {
                return ((string)(this["c0_hourx_G"]));
            }
            set {
                this["c0_hourx_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_hourx_B {
            get {
                return ((string)(this["c0_hourx_B"]));
            }
            set {
                this["c0_hourx_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_hourx_O {
            get {
                return ((string)(this["c0_hourx_O"]));
            }
            set {
                this["c0_hourx_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_hourx_S {
            get {
                return ((string)(this["c0_hourx_S"]));
            }
            set {
                this["c0_hourx_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_hourx_F {
            get {
                return ((string)(this["c0_hourx_F"]));
            }
            set {
                this["c0_hourx_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_midx_R {
            get {
                return ((string)(this["c0_midx_R"]));
            }
            set {
                this["c0_midx_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_midx_G {
            get {
                return ((string)(this["c0_midx_G"]));
            }
            set {
                this["c0_midx_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_midx_B {
            get {
                return ((string)(this["c0_midx_B"]));
            }
            set {
                this["c0_midx_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_midx_O {
            get {
                return ((string)(this["c0_midx_O"]));
            }
            set {
                this["c0_midx_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_midx_S {
            get {
                return ((string)(this["c0_midx_S"]));
            }
            set {
                this["c0_midx_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_midx_F {
            get {
                return ((string)(this["c0_midx_F"]));
            }
            set {
                this["c0_midx_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_cifx_R {
            get {
                return ((string)(this["c0_cifx_R"]));
            }
            set {
                this["c0_cifx_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_cifx_G {
            get {
                return ((string)(this["c0_cifx_G"]));
            }
            set {
                this["c0_cifx_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_cifx_B {
            get {
                return ((string)(this["c0_cifx_B"]));
            }
            set {
                this["c0_cifx_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_cifx_O {
            get {
                return ((string)(this["c0_cifx_O"]));
            }
            set {
                this["c0_cifx_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_cifx_S {
            get {
                return ((string)(this["c0_cifx_S"]));
            }
            set {
                this["c0_cifx_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_cifx_F {
            get {
                return ((string)(this["c0_cifx_F"]));
            }
            set {
                this["c0_cifx_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_podx_R {
            get {
                return ((string)(this["c0_podx_R"]));
            }
            set {
                this["c0_podx_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_podx_G {
            get {
                return ((string)(this["c0_podx_G"]));
            }
            set {
                this["c0_podx_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_podx_B {
            get {
                return ((string)(this["c0_podx_B"]));
            }
            set {
                this["c0_podx_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_podx_O {
            get {
                return ((string)(this["c0_podx_O"]));
            }
            set {
                this["c0_podx_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_podx_S {
            get {
                return ((string)(this["c0_podx_S"]));
            }
            set {
                this["c0_podx_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c0_podx_F {
            get {
                return ((string)(this["c0_podx_F"]));
            }
            set {
                this["c0_podx_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_CI_R {
            get {
                return ((string)(this["w_CI_R"]));
            }
            set {
                this["w_CI_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_CI_G {
            get {
                return ((string)(this["w_CI_G"]));
            }
            set {
                this["w_CI_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_CI_B {
            get {
                return ((string)(this["w_CI_B"]));
            }
            set {
                this["w_CI_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_CI_O {
            get {
                return ((string)(this["w_CI_O"]));
            }
            set {
                this["w_CI_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_CI_S {
            get {
                return ((string)(this["w_CI_S"]));
            }
            set {
                this["w_CI_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_CI_F {
            get {
                return ((string)(this["w_CI_F"]));
            }
            set {
                this["w_CI_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_TEMP_R {
            get {
                return ((string)(this["w_TEMP_R"]));
            }
            set {
                this["w_TEMP_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_TEMP_G {
            get {
                return ((string)(this["w_TEMP_G"]));
            }
            set {
                this["w_TEMP_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_TEMP_B {
            get {
                return ((string)(this["w_TEMP_B"]));
            }
            set {
                this["w_TEMP_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_TEMP_O {
            get {
                return ((string)(this["w_TEMP_O"]));
            }
            set {
                this["w_TEMP_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_TEMP_S {
            get {
                return ((string)(this["w_TEMP_S"]));
            }
            set {
                this["w_TEMP_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_TEMP_F {
            get {
                return ((string)(this["w_TEMP_F"]));
            }
            set {
                this["w_TEMP_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_INFO_R {
            get {
                return ((string)(this["w_INFO_R"]));
            }
            set {
                this["w_INFO_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_INFO_G {
            get {
                return ((string)(this["w_INFO_G"]));
            }
            set {
                this["w_INFO_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_INFO_B {
            get {
                return ((string)(this["w_INFO_B"]));
            }
            set {
                this["w_INFO_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_INFO_O {
            get {
                return ((string)(this["w_INFO_O"]));
            }
            set {
                this["w_INFO_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_INFO_S {
            get {
                return ((string)(this["w_INFO_S"]));
            }
            set {
                this["w_INFO_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_INFO_F {
            get {
                return ((string)(this["w_INFO_F"]));
            }
            set {
                this["w_INFO_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_OBR_nofont_R {
            get {
                return ((string)(this["w_OBR_nofont_R"]));
            }
            set {
                this["w_OBR_nofont_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_OBR_nofont_G {
            get {
                return ((string)(this["w_OBR_nofont_G"]));
            }
            set {
                this["w_OBR_nofont_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_OBR_nofont_B {
            get {
                return ((string)(this["w_OBR_nofont_B"]));
            }
            set {
                this["w_OBR_nofont_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_OBR_nofont_O {
            get {
                return ((string)(this["w_OBR_nofont_O"]));
            }
            set {
                this["w_OBR_nofont_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_OBR_nofont_S {
            get {
                return ((string)(this["w_OBR_nofont_S"]));
            }
            set {
                this["w_OBR_nofont_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_OBR_nofont_F {
            get {
                return ((string)(this["w_OBR_nofont_F"]));
            }
            set {
                this["w_OBR_nofont_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_DATUM_R {
            get {
                return ((string)(this["w_DATUM_R"]));
            }
            set {
                this["w_DATUM_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_DATUM_G {
            get {
                return ((string)(this["w_DATUM_G"]));
            }
            set {
                this["w_DATUM_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_DATUM_B {
            get {
                return ((string)(this["w_DATUM_B"]));
            }
            set {
                this["w_DATUM_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_DATUM_O {
            get {
                return ((string)(this["w_DATUM_O"]));
            }
            set {
                this["w_DATUM_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_DATUM_S {
            get {
                return ((string)(this["w_DATUM_S"]));
            }
            set {
                this["w_DATUM_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string w_DATUM_F {
            get {
                return ((string)(this["w_DATUM_F"]));
            }
            set {
                this["w_DATUM_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_msecx_R {
            get {
                return ((string)(this["c1_msecx_R"]));
            }
            set {
                this["c1_msecx_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_msecx_G {
            get {
                return ((string)(this["c1_msecx_G"]));
            }
            set {
                this["c1_msecx_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_msecx_B {
            get {
                return ((string)(this["c1_msecx_B"]));
            }
            set {
                this["c1_msecx_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_msecx_O {
            get {
                return ((string)(this["c1_msecx_O"]));
            }
            set {
                this["c1_msecx_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_msecx_S {
            get {
                return ((string)(this["c1_msecx_S"]));
            }
            set {
                this["c1_msecx_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_msecx_F {
            get {
                return ((string)(this["c1_msecx_F"]));
            }
            set {
                this["c1_msecx_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_secx_R {
            get {
                return ((string)(this["c1_secx_R"]));
            }
            set {
                this["c1_secx_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_secx_G {
            get {
                return ((string)(this["c1_secx_G"]));
            }
            set {
                this["c1_secx_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_secx_B {
            get {
                return ((string)(this["c1_secx_B"]));
            }
            set {
                this["c1_secx_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_secx_O {
            get {
                return ((string)(this["c1_secx_O"]));
            }
            set {
                this["c1_secx_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_secx_S {
            get {
                return ((string)(this["c1_secx_S"]));
            }
            set {
                this["c1_secx_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_secx_F {
            get {
                return ((string)(this["c1_secx_F"]));
            }
            set {
                this["c1_secx_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_minx_R {
            get {
                return ((string)(this["c1_minx_R"]));
            }
            set {
                this["c1_minx_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_minx_G {
            get {
                return ((string)(this["c1_minx_G"]));
            }
            set {
                this["c1_minx_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_minx_B {
            get {
                return ((string)(this["c1_minx_B"]));
            }
            set {
                this["c1_minx_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_minx_O {
            get {
                return ((string)(this["c1_minx_O"]));
            }
            set {
                this["c1_minx_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_minx_S {
            get {
                return ((string)(this["c1_minx_S"]));
            }
            set {
                this["c1_minx_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_minx_F {
            get {
                return ((string)(this["c1_minx_F"]));
            }
            set {
                this["c1_minx_F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_hourx_R {
            get {
                return ((string)(this["c1_hourx_R"]));
            }
            set {
                this["c1_hourx_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_hourx_G {
            get {
                return ((string)(this["c1_hourx_G"]));
            }
            set {
                this["c1_hourx_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_hourx_B {
            get {
                return ((string)(this["c1_hourx_B"]));
            }
            set {
                this["c1_hourx_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_hourx_O {
            get {
                return ((string)(this["c1_hourx_O"]));
            }
            set {
                this["c1_hourx_O"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_hourx_S {
            get {
                return ((string)(this["c1_hourx_S"]));
            }
            set {
                this["c1_hourx_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string c1_hourx_F {
            get {
                return ((string)(this["c1_hourx_F"]));
            }
            set {
                this["c1_hourx_F"] = value;
            }
        }
    }
}
